name: 'Trigger - Helm Chart Image Updater'
description: 'Trigger image updating'
inputs:
  git-repo: 
    description: 'GitHub Repository to look for Chart.yaml in'
    required: true
    default: ''
  chart-location: 
    description: 'Location of Helm Chart.yaml'
    required: true
    default: ''
  appversion:
    description: 'appVersion to replace in Helm Chart'
    required: true
    default: ''
  actions-pat-key:
    description: 'GitHub Personal Access Token to do perform an authenticated request to trigger Helm Image Updater'
    required: true
    default: ''
outputs:
  result:
    description: "Result"
    value: ${{ steps.helm-image-updater-trigger-action.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: helm-image-updater-trigger-action
      shell: bash
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: ${{ inputs.actions-pat-key }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ inputs.git-repo }}/dispatches \
        -d '{"event_type":"bump_appversion","client_payload":{"appversion": "${{ inputs.appversion }}", "helmchartdir": "${{ inputs.chart-location }}"}}'
  